[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ed-explorer-stats"
version = "0.1.0"
dependencies = [
	"colorama",
]

[project.scripts]
explorer-stats = "ed_explorer_stats.exploration_stats:main"